### ISSUE TITLE
./configure fails against: unexpected token `RANDR,'

### ISSUE THREAD

**Issue by JacekJaworski** [merge/xf86-input-tslib#9]
Hi
I try to compile xf86-input-tslib, but it failed. I try execute autogen.sh and it fail with suggestion to instal
sudo apt-get install xutils-dev
I did this. Next I invoke ./configure and it failed with following message:

./configure: line 18549: syntax error near unexpected token `RANDR,'
./configure: line 18549: `XORG_DRIVER_CHECK_EXT(RANDR, randrproto)'

What I am supposed to do?!?
Rasbian is fully updated...
thanks and best regards
Jacek

**Comment by JacekJaworski** [comment]
The solution was:
sudo apt-get install xorg-dev
Then:
autogen-clean.sh
autogen.sh
configure
and then it woks, and I be able to compile...

**Comment by alegator-cs** [comment]
This issue was helpful while building SVGA3D: https://mesa-docs.readthedocs.io/en/latest/vmware-guest.html
I had a similar error for xf86-video-vmware, during the autogen step, and installing xorg-dev, then cloning a fresh repository for xf86-video-vmware, allowed the installation to complete.
